rootProject.name = 'magicbox'

include 'services:user'
include 'services:auth'
include 'services:subscribe'
include 'services:creator'
include 'services:general-goods'
include 'services:orchestrator'
include 'services:delivery'
include 'services:payment'
include 'services:settlement'
include 'services:release'
include 'services:waiting'
include 'services:order'
include 'services:search'
include 'services:sse-gateway'
include 'services:review'