package kr.magicbox.notification.domain.enums;

public enum NotificationType {
    // User
    USER_SIGNUP,
    USER_BANNED,
    USER_UNBANNED,
    USER_DUPLICATE_LOGGED_IN,

    // Creator
    CREATOR_CERTIFICATION_APPROVED,
    CREATOR_CERTIFICATION_REJECTED,
    CREATOR_REVOKED,
    CREATOR_UNBANNED,

    // Release
    RELEASE_CREATED,
    RELEASE_UPDATED,
    STOCK_RESERVE_SUCCEEDED,
    STOCK_RESERVE_FAILED,

    // Order
    ORDER_PREPARE,
    ORDER_CONFIRMED,
    ORDER_DELIVERED,
    ORDER_CANCEL,
    ORDER_PURCHASE_CONFIRMED,
    ORDER_AUTO_CONFIRMED,

    // Payment
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_CANCEL_SUCCEEDED,
    PAYMENT_CANCEL_FAILED,

    // Delivery
    DELIVERY_STARTED,
    DELIVERY_COMPLETED,

    // General Goods
    GENERAL_GOODS_CREATED,
    GENERAL_GOODS_UPDATED
}
