spring:
  application:
    name: settlement-local
  jackson:
    property-naming-strategy: SNAKE_CASE
  config:
    import:
      - optional:file:services/settlement/env/local.env[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      ack-mode: record
      missing-topics-fatal: false
    consumer:
      group-id: settlement-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: "kr.magicbox.settlement.adapter.in.kafka.event"
        spring.json.type.mapping: settlement-ready:kr.magicbox.settlement.adapter.in.kafka.event.SettlementReadyCommandEvent,settlement-settle:kr.magicbox.settlement.adapter.in.kafka.event.SettlementSettleCommandEvent,payment-cancel-succeeded:kr.magicbox.settlement.adapter.in.kafka.event.PaymentCancelSucceededEvent
    retry:
      topic:
        attempts: 3
        backoff:
          delay: 1s
          max-delay: 3s
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/settlement}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${SERVER_PORT:8100}

inbox:
  max-event-age-minutes: 5
