spring:
  application:
    name: settlement-dev
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    listener:
      ack-mode: record
      missing-topics-fatal: false
    consumer:
      group-id: settlement-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: "kr.magicbox.settlement.adapter.in.kafka.event"
        spring.json.type.mapping: settlement-ready:kr.magicbox.settlement.adapter.in.kafka.event.SettlementReadyCommandEvent,settlement-settle:kr.magicbox.settlement.adapter.in.kafka.event.SettlementSettleCommandEvent,payment-cancel-succeeded:kr.magicbox.settlement.adapter.in.kafka.event.PaymentCancelSucceededEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topic:
        attempts: 3
        backoff:
          delay: 1s
          max-delay: 3s
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

inbox:
  max-event-age-minutes: 5
