spring:
  application:
    name: general-goods-local
  config:
    import:
      - file:services/general-goods/env/local.env[.properties]

server:
  port: ${SERVER_PORT}

inbox:
  max-event-age-minutes: 5
