package kr.magicbox.shortform.domain.enums;

public enum MagicGenre {
    CLOSE_UP,
    STREET_MAGIC,
    PARLOR_MAGIC,
    STAGE_MAGIC,
    GRAND_ILLUSION,
    BUSKING_MAGIC,
    CARD_MAGIC,
    COIN_MAGIC,
    CARDISTRY,
    MANIPULATION,
    ROPE_MAGIC,
    SILK_MAGIC,
    DOVE_MAGIC,
    CUPS_AND_BALLS,
    SPONGE_BALL,
    LINKING_RINGS,
    MENTALISM,
    ESCAPOLOGY,
    PICKPOCKET_MAGIC,
    COMEDY_MAGIC,
    KIDS_MAGIC,
    CORPORATE_MAGIC,
    MUSICAL_MAGIC,
    VIRTUAL_MAGIC
}
