spring:
  application:
    name: release-local
  jackson:
    property-naming-strategy: SNAKE_CASE
  config:
    import:
      - file:services/release/env/local.env[.properties]
  grpc:
    server:
      port: ${GRPC_SERVER_PORT}
    client:
      channels:
        creator-service:
          address: ${CREATOR_SERVICE_URL}
          negotiation-type: plaintext
          keep-alive-time: 30s
          keep-alive-timeout: 5s
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${SERVER_PORT}

security:
  trusted:
    ips:
      - 127.0.0.1
      - 0:0:0:0:0:0:0:1

resilience4j:
  circuitbreaker:
    instances:
      creatorService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      creatorService:
        timeout-duration: 2s
