spring:
  application:
    name: subscribe-prod
  jackson:
    property-naming-strategy: SNAKE_CASE
  grpc:
    server:
      port: ${GRPC_SERVER_PORT}
    client:
      channels:
        creator:
          address: ${CREATOR_SERVICE_URL}
          negotiation-type: plaintext
          keep-alive-time: 30s
          keep-alive-timeout: 5s
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    listener:
      ack-mode: record
      missing-topics-fatal: true
    consumer:
      group-id: subscribe-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: "kr.magicbox.subscribe.adapter.in.kafka.event"
        spring.json.type.mapping: user-withdrawn:kr.magicbox.subscribe.adapter.in.kafka.event.UserWithdrawnEvent,user-banned:kr.magicbox.subscribe.adapter.in.kafka.event.UserBannedEvent,creator-revoked:kr.magicbox.subscribe.adapter.in.kafka.event.CreatorRevokedEvent
    retry:
      topic:
        backoff:
          multiplier: 2
          delay: 1s
        attempts: 5
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

security:
  trusted:
    ips:
      - ${TRUSTED_IP_GATEWAY}

inbox:
  max-event-age-minutes: 5
