version = '0.0.1'
description = 'settlement'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation 'org.springframework:spring-aspects'
    implementation 'org.aspectj:aspectjweaver'
    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    runtimeOnly 'com.mysql:mysql-connector-j'

    testImplementation 'org.springframework.kafka:spring-kafka-test'
}
