waiting:
  avg-purchase-seconds: ${WAITING_AVG_PURCHASE_SECONDS:30}
  purchase-token-ttl-seconds: ${WAITING_PURCHASE_TOKEN_TTL_SECONDS:300}
  polling-interval-seconds: ${WAITING_POLLING_INTERVAL_SECONDS:10}
  queue-key-prefix: ${WAITING_QUEUE_KEY_PREFIX:waiting:}
  user-release-key-prefix: ${WAITING_USER_RELEASE_KEY_PREFIX:user_release:}
  token-key-prefix: ${WAITING_TOKEN_KEY_PREFIX:purchase_token:}
  admission-decrease-ratio: ${WAITING_ADMISSION_DECREASE_RATIO:0.9}
  admission-max-batch-ratio: ${WAITING_ADMISSION_MAX_BATCH_RATIO:0.2}
  admission-initial-batch-ratio-percent: ${WAITING_ADMISSION_INITIAL_BATCH_RATIO_PERCENT:10}

spring:
  application:
    name: waiting-local
  config:
    import:
      - file:services/waiting/env/local.env[.properties]

server:
  port: ${SERVER_PORT}