spring:
  application:
    name: waiting-local
  jackson:
    property-naming-strategy: SNAKE_CASE
  config:
    import:
      - file:services/waiting/env/local.env[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  grpc:
    server:
      port: ${GRPC_SERVER_PORT}
    client:
      channels:
        release-service:
          address: ${RELEASE_SERVICE_URL}
          negotiation-type: plaintext
          keep-alive-time: 30s
          keep-alive-timeout: 5s

server:
  port: ${SERVER_PORT}

security:
  trusted:
    ips:
      - 127.0.0.1
      - 0:0:0:0:0:0:0:1
